-- MySQL Script generated by MySQL Workbench
-- Tue Aug 30 21:51:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_de_ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_de_ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_de_ventas` DEFAULT CHARACTER SET utf8 ;
USE `sistema_de_ventas` ;

-- -----------------------------------------------------
-- Table `sistema_de_ventas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_de_ventas`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `numero_documento` VARCHAR(15) NOT NULL,
  `tipo_usuario` VARCHAR(20) NOT NULL,
  `nombre_usuario` VARCHAR(30) NOT NULL,
  `contrasenia_usuario` VARCHAR(200) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_de_ventas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_de_ventas`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `numero_documento` VARCHAR(15) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_de_ventas`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_de_ventas`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NOT NULL,
  `precio_compra` DECIMAL(18,2) NOT NULL,
  `precio_venta` DECIMAL(18,2) NOT NULL,
  `stock` INT NOT NULL,
  `unidad_medida` VARCHAR(30) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_de_ventas`.`comprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_de_ventas`.`comprobantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `serie` VARCHAR(6) NULL,
  `numero` VARCHAR(16) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_de_ventas`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_de_ventas`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `idcomprobante` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `numero_comprante` VARCHAR(14) NOT NULL,
  `subtotal` DECIMAL(18,2) NOT NULL,
  `itbis` DECIMAL(18,2) NOT NULL,
  `total` DECIMAL(18,2) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_CLIENTES_idx` (`idcliente` ASC),
  INDEX `FK_USUARIOS_idx` (`idusuario` ASC),
  INDEX `FK_COMPROBANTE_idx` (`idcomprobante` ASC),
  CONSTRAINT `FK_CLIENTES`
    FOREIGN KEY (`idcliente`)
    REFERENCES `sistema_de_ventas`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USUARIOS`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sistema_de_ventas`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMPROBANTE`
    FOREIGN KEY (`idcomprobante`)
    REFERENCES `sistema_de_ventas`.`comprobantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_de_ventas`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_de_ventas`.`detalle_ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idventa` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(18,2) NOT NULL,
  `subtotal` DECIMAL(18,2) NOT NULL,
  `itbis` DECIMAL(18,2) NOT NULL,
  `total` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_VENTAS_DETALLE_idx` (`idventa` ASC),
  INDEX `FK_PRODUCTO_DETALLE_idx` (`idproducto` ASC),
  CONSTRAINT `FK_VENTAS_DETALLE`
    FOREIGN KEY (`idventa`)
    REFERENCES `sistema_de_ventas`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCTO_DETALLE`
    FOREIGN KEY (`idproducto`)
    REFERENCES `sistema_de_ventas`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
